### ISSUE TITLE
Prettier --write found some errors

### ISSUE THREAD

**Issue by btd1337** [schuchard/prettier-schematic#9]
When I run the command `npm run prettier` or try to commit, this error happens. What could be wrong?

`prettier --write found some errors. Please fix them and try committing again.`

```
/../node_modules/.bin/prettier: linha 1: use strict: command not found
/../node_modules/.bin/prettier: linha 2: syntax error next to unexpected token `exports,'
/../node_modules/.bin/prettier: linha 2: `Object.defineProperty(exports, "__esModule", { value: true });'
husky > pre-commit hook failed (add --no-verify to bypass)
```
**Log File:**

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'prettier' ]
2 info using npm@6.4.1
3 info using node@v11.2.0
4 verbose run-script [ 'prettier' ]
5 info lifecycle projectX~prettier: projectX
6 verbose lifecycle projectX~prettier: unsafe-perm in lifecycle true
7 verbose lifecycle projectX~prettier: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/desenvolvimento/Trabalho/Pontta/projectX/node_modules/.bin:/home/arch/.yarn/bin:/home/arch/.config/yarn/global/node_modules/.bin:/home/arch/.npm-global/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
8 verbose lifecycle projectX~prettier: CWD: /opt/desenvolvimento/Trabalho/Pontta/projectX
9 silly lifecycle projectX~prettier: Args: [ '-c',
9 silly lifecycle   'prettier --write "**/*.{js,json,css,md,ts,html,component.html}"' ]
10 silly lifecycle projectX~prettier: Returned: code: 2  signal: null
11 info lifecycle projectX~prettier: Failed to exec prettier script
12 verbose stack Error: projectX prettier: `prettier --write "**/*.{js,json,css,md,ts,html,component.html}"`
12 verbose stack Exit status 2
12 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
12 verbose stack     at EventEmitter.emit (events.js:182:13)
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
12 verbose stack     at ChildProcess.emit (events.js:182:13)
12 verbose stack     at maybeClose (internal/child_process.js:978:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
13 verbose pkgid projectX
14 verbose cwd /opt/desenvolvimento/Trabalho/Pontta/projectX
15 verbose Linux 4.19.2-arch1-1-ARCH
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "prettier"
17 verbose node v11.2.0
18 verbose npm  v6.4.1
19 error code ELIFECYCLE
20 error errno 2
21 error projectX prettier: `prettier --write "**/*.{js,json,css,md,ts,html,component.html}"`
21 error Exit status 2
22 error Failed at the projectX prettier script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 2, true ]
```

My `prettier.config` file

```
module.exports = {
	printWidth: 80,
	tabWidth: 2,
	useTabs: true,
	semi: false,
	singleQuote: true,
	trailingComma: 'none',
	bracketSpacing: true,
	jsxBracketSameLine: false,
	arrowParens: 'avoid',
	rangeStart: 0,
	rangeEnd: Infinity,
	parser: 'angular',
	requirePragma: false,
	insertPragma: false,
	proseWrap: 'always'
};

```

**Comment by schuchard** [comment]
Try removing the `parser` entry from your prettier.config. The parser is inferred from the file path - https://prettier.io/docs/en/options.html#parser

If that doesn't work can you identify the file(s) that start with `use strict`? These errors appear to be pointing to a file Prettier is unable to parse.

```bash
/../node_modules/.bin/prettier: linha 1: use strict: command not found
/../node_modules/.bin/prettier: linha 2: syntax error next to unexpected token `exports,'
/../node_modules/.bin/prettier: linha 2: `Object.defineProperty(exports, "__esModule", { value: true });'
```

you also might be running prettier against compiled/build files and may want to ignore a `dist` folder for example. That can be done in the .prettierignore [file](https://github.com/schuchard/prettier-schematic/blob/master/src/prettier/files/.prettierignore).

Finally, try running with the debug logs to see if that provides any additional info: `--loglevel=debug`

```
"prettier": "prettier --loglevel=debug --write \"**/*.{js,json,css,md,ts,html,component.html}\"",```

**Comment by btd1337** [comment]
Removing the `Parser` solved for me. Thanks!
